### ISSUE TITLE
Question: Did you advance on this?

### ISSUE THREAD

**Issue by joschne** [jagreehal/nextjs-stenciljs-ssr-example#3]
Hi @jagreehal 

I need a solution to render stencil web components on the server side with nextjs. 

In my research I came across this repo – it addresses exactly my problem, but solves it only partially and three years passed by since you worked on it.   

Did you advance on this topic? How do you solve the issue today?
Any answer would be very appreciated, thanks!

**Comment by jagreehal** [comment]
@joschne so I'm glad I never pushed or pursued this solution to any of my clients. 

I don't think this will ever be production ready, there are just too many trade-offs.

I updated the example to use React 17 and while you're able to server side render Stencil components using a custom server, you start to see why this isn't great.

With React 18 and Next 12 onwards, I couldn't resolve the hydration issues. 

Even if I could, I'm not convinced SSR or hydration are priorities for the Stencil team, so you may find yourself with little support if you hit issues.
